# Generated by Django 2.2.4 on 2019-08-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eximp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('paradign', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='eximp',
            options={'verbose_name_plural': 'ExImp'},
        ),
    ]
